In [1]:
#Q1:Import the numpy package under the name np (★☆☆)
import numpy as np

In [3]:
#Q2: Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.show_config())

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-j8vn_sl2/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-j8vn_sl2/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-j8vn_sl2/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-j8vn_sl2/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

In [5]:
#Q3: Create a null vector of size 10 (★☆☆)
array1=np.zeros(10,dtype=int)
print(array1)

[0 0 0 0 0 0 0 0 0 0]


In [7]:
#Q4:How to find the memory size of any array (★☆☆)
print(array1.nbytes) #Array 1 is created in question 3

80


In [14]:
#Q5: How to get the documentation of the numpy add function from the command line? (★☆☆)
help(np.add)#In jupyter notebook

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [21]:
#Q6: Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
array1[4]=1#Array 1 is created in question 3
print(array1)

[0 0 0 0 1 0 0 0 0 0]


In [23]:
#Q7: Create a vector with values ranging from 10 to 49 
array2=np.arange(10,50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [32]:
#Q8:Reverse a vector (first element becomes last) (★☆☆)
print(array2[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [40]:
#Q9: Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
array3=np.arange(9).reshape(3,3)
print(array3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
#Q10: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array4=np.array([1,2,0,0,4,0])
print(np.nonzero(array4))

(array([0, 1, 4]),)
